name: Pull Request on Main

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  validate-pr:
    uses: ./.github/workflows/validate.yml
    with:
      changeset:
        ${{ !contains(github.event.pull_request.title, '[skip changeset]') &&
        !contains(github.event.pull_request.title, 'repo') &&
        !contains(github.event.pull_request.title, 'ci') }}
      commitlint_mode: 'pr'
