name: Push on Main

on:
  push:
    branches:
      - main

permissions:
  pull-requests: write # Allow creating PRs
  contents: write # Allow pushing changes to the repository

jobs:
  validate:
    uses: ./.github/workflows/validate.yml

  changesets:
    needs: validate
    runs-on: ubuntu-latest
    if: |
      !(
        contains(github.event.head_commit.message, '[skip changeset]') ||
        contains(github.event.head_commit.message ,'repo') ||
        contains(github.event.head_commit.message, 'ci')
      )
    steps:
      - name: â¬‡ï¸ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ“¦ Setup Environment
        uses: ./.github/actions/setup-env

      - name: âœï¸ Create Version PR (Changesets)
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
