name: Push on Any Non-Main Branch

on:
  push:
    branches-ignore:
      - main

jobs:
  validate:
    uses: ./.github/workflows/validate.yml
    with:
      changeset: false

  commitlint:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ“¦ Setup Environment
        uses: ./.github/actions/setup-env

      - name: ğŸ“ Validate Commit Message (Commitlint)
        run: |
          echo "Validating last commit..."
          npx commitlint --last --verbose
        shell: bash
